/**
 * Force crypto.randomUUID to return a deterministic value so tests can
 * reliably assert on entity ids generated by Profile/Category/Item.
 */
;(globalThis.crypto as any).randomUUID = () => '00000000-0000-4000-8000-000000000000'

// Vuetify relies on ResizeObserver, which jsdom does not implement.
class ResizeObserverMock {
    observe() {}
    unobserve() {}
    disconnect() {}
}

globalThis.ResizeObserver = ResizeObserverMock as unknown as typeof ResizeObserver

// Vuetify may query matchMedia for responsive behavior. jsdom lacks it.
if (typeof window !== 'undefined' && !window.matchMedia) {
    window.matchMedia = ((query: string) => ({
        matches: false,
        media: query,
        onchange: null,
        addListener: () => {},
        removeListener: () => {},
        addEventListener: () => {},
        removeEventListener: () => {},
        dispatchEvent: () => false
    })) as unknown as typeof window.matchMedia
}

// Vuetify's VOverlay reads window.visualViewport, which jsdom does not implement.
if (typeof window !== 'undefined' && !window.visualViewport) {
    // @ts-expect-error - minimal mock for jsdom
    window.visualViewport = {
        width: 0,
        height: 0,
        offsetLeft: 0,
        offsetTop: 0,
        pageLeft: 0,
        pageTop: 0,
        scale: 1,
        addEventListener: () => {},
        removeEventListener: () => {},
        dispatchEvent: () => false
    }
}
