const { defineConfig } = require('@vue/cli-service');
const webpack = require('webpack');

module.exports = defineConfig({
  // This tells the output to use relative URLs instead of absolute. We need this because Electron
  // loads the dist/index.html file, but can't find the scripts generated by the vue cli when they
  // have a / in front of the path name. This option gets rid of the beginning slash
  publicPath: './',
  transpileDependencies: true,
  pluginOptions: {
    electronBuilder: {
      customFileProtocol: './',
      builderOptions: {
      }
    }
  },
  configureWebpack:{
    resolve: {
      fallback: { 
        "crypto": require.resolve("crypto-browserify"),
        "stream": require.resolve("stream-browserify"),
        "buffer": require.resolve('buffer')
      }
    },
    plugins:[
      new webpack.ProvidePlugin({
        Buffer: ['buffer', 'Buffer'],
      }),
    ]
    
  }
});
